### PR TITLE
Attempt to add support for Apache Royale with fallback to FlexJS

### PR DESCRIPTION
**Pull request by Harbs**
I hope this is useful for supporting Royale. I tried to keep this backwards compatible.

Right now it looks like it's using MXMLJSC instead of MXMLC, but I'm not sure why.

### CODE REVIEW

**Comment by Harbs** [comment]
Travis is failing because it's using the FlexJS SDK. I'm not sure how to install a Royale SDK on Travis before we make the first Royale release.

**Comment by joshtynjala** [comment]
Thanks, @Harbs. I'll try to take a look sometime this week!

**Comment by Harbs** [comment]
FWIW, for complete support, npm will need to be setup for Royale. I'm not 100% positive that I used the correct name for that.

FYI I also started looking at the VS Code extension, but I was able to get basic support in VS Code be just using the updated version of asconfigc.

**Comment by joshtynjala** [comment]
When I build royale-asjs from the develop branch, I can't find *royale-sdk-description.xml* or *frameworks/royale-config.xml*. The root element in the config.xml files is still `<flex-config>` instead of `<royale-config>` too. Are they on a different branch that hasn't been merged into develop yet?

**Comment by Harbs** [comment]
Yes. feature/rename

**Comment by joshtynjala** [comment]
Thanks for the branch name! I could use that branch to build a distribution and test it with asconfigc.

I made it so asconfigc can now handle both Royale and FlexJS, and I fixed up some things related to building with other SDKs (like the Feathers SDK and Adobe's AIR SDK & Compiler). All tests are passing with both Royale and FlexJS. On the CI server, tests pass with FlexJS. I've merged these changes into the master branch, and they'll be included in the next update after I finish up the AIR packaging stuff.

**Pull request closed without merging**
